# requires the package `ttf-font-awesome`
icons = "awesome5"

[[block]]
block = "sound"

[[block]]
block = "music"
player = "spotify"
buttons = ["play", "next"]

[[block]]
block = "networkmanager"
on_click = "alacritty -e nmtui"
interface_name_exclude = ["br\\-[0-9a-f]{12}", "docker\\d+"]
interface_name_include = []
max_ssid_width = 12
ap_format = "{ssid} ({strength}%)"

[[block]]
block = "disk_space"
path = "/"
alias = ""
info_type = "available"
unit = "GiB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
format_mem = "{Mug} GiB"
format_swap = "{SUg} GiB"
display_type = "memory"
icons = true
clickable = true
interval = 5
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "temperature"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
